name: 2twenty2 Photography
favicon: null
layout_spectrum: 0.5217010038904846
typography_spectrum: 0.12211287044920027
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#81a847'
    - '#c3c3c3'
    - '#425f21'
  brandStrength: 0.625
  lightness: 1
  saturation: 0.4211706090718508
  rhythmicContrast: 0.75
purpose: []
