name: 2twenty2 Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26925
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#81a847'
    - '#c3c3c3'
    - '#425f21'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
